
[passwords]
username = "user01"
admin = "admin"


[theme]
primaryColor = "#1E90FF"  # Dodger Blue
backgroundColor = "#F0F8FF"  # Alice Blue
secondaryBackgroundColor = "#ADD8E6"  # Light Blue
textColor = "#000080"  # Navy Blue